apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shporodom
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: app
  source:
    path: "Helm/MainChart"
    repoURL: "git@github.com:serglit72/argocd-devops.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: serglit72/shporodom:v0.1.5

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
